version: "3"

services:
  powerswitch:
    container_name: hp-ilo-powerswitch
    image: hp-ilo-powerswitch
    ports:
      - 5000:5000
    environment:
      # specify values without quotes
      - ILOHOST=<host>
      - ILOUSER=<user>
      - ILOPASS=<password>
      - SERVERTOKEN=<servertoken>

    restart: unless-stopped