version: "3"

services:
  powerswitch:
    container_name: hp-ilo-powerswitch
    image: hp-ilo-powerswitch

    network_mode: "host"
    ports:
      - 5000:5000
    environment:
      # specify values without quotes
      - USER=<username>
      - PASS=<password>
      - ILOHOST=<host>
      - ILOUSER=<user>
      - ILOPASS=<password>